// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_up6goSlfs8eOH2C51zM6ViIazeU-w8',
    appId: '1:523935837025:web:c54a0c1993b54a5bccf320',
    messagingSenderId: '523935837025',
    projectId: 'redsea-shop-23e0a',
    authDomain: 'redsea-shop-23e0a.firebaseapp.com',
    storageBucket: 'redsea-shop-23e0a.firebasestorage.app',
    measurementId: 'G-J4820YK9PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfV4HkWzy33k4tsEgoBh5mYI99z4u_4Vo',
    appId: '1:523935837025:android:0c3f5c978761b536ccf320',
    messagingSenderId: '523935837025',
    projectId: 'redsea-shop-23e0a',
    storageBucket: 'redsea-shop-23e0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM6ypK0m87mhgrgvfQxh8QEIKBNmm8Hkw',
    appId: '1:523935837025:ios:87cbad353b8e080fccf320',
    messagingSenderId: '523935837025',
    projectId: 'redsea-shop-23e0a',
    storageBucket: 'redsea-shop-23e0a.firebasestorage.app',
    iosBundleId: 'com.example.redsea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6ypK0m87mhgrgvfQxh8QEIKBNmm8Hkw',
    appId: '1:523935837025:ios:87cbad353b8e080fccf320',
    messagingSenderId: '523935837025',
    projectId: 'redsea-shop-23e0a',
    storageBucket: 'redsea-shop-23e0a.firebasestorage.app',
    iosBundleId: 'com.example.redsea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_up6goSlfs8eOH2C51zM6ViIazeU-w8',
    appId: '1:523935837025:web:622c7cbef4d23306ccf320',
    messagingSenderId: '523935837025',
    projectId: 'redsea-shop-23e0a',
    authDomain: 'redsea-shop-23e0a.firebaseapp.com',
    storageBucket: 'redsea-shop-23e0a.firebasestorage.app',
    measurementId: 'G-B667KS997B',
  );
}
